version: '3.8'

services:
  web:
    build:
      context: .
      target: webapp
    container_name: krykun-war
    depends_on:
      - db
    ports:
      - 8080:8080


  db:
    build:
      context: .
      target: db
    container_name: krykun-database
    ports:
      - 9092:9092